package com.example.data.firebase

import android.content.Context
import android.util.Log
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions
import kotlinx.coroutines.tasks.await
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import com.google.firebase.FirebaseNetworkException
import com.google.firebase.auth.FirebaseAuthException
import com.google.firebase.auth.FirebaseAuthInvalidCredentialsException
import com.google.firebase.auth.GoogleAuthProvider

enum class FirebaseSyncStatus {
    REAL_SUCCESS,
    OFFLINE_MODE,
    ERROR
}

data class FirebaseSyncResult(
    val status: FirebaseSyncStatus,
    val message: String,
    val uid: String? = null,
    val email: String? = null,
    val displayName: String? = null,
    val isEmailVerified: Boolean = false
) {
    val isRealSuccess: Boolean get() = status == FirebaseSyncStatus.REAL_SUCCESS
    val isOfflineMode: Boolean get() = status == FirebaseSyncStatus.OFFLINE_MODE
    val isError: Boolean get() = status == FirebaseSyncStatus.ERROR

    // CRITICAL: success is strictly true ONLY when real remote Firebase operation succeeded.
    // It is NEVER true for OFFLINE_MODE or ERROR.
    val success: Boolean get() = status == FirebaseSyncStatus.REAL_SUCCESS
}

class FirebaseManager(private val context: Context) {

    companion object {
        private const val TAG = "FirebaseManager"

        /**
         * Requirement 22: Validates that a Firestore document ID in `/users/{uid}` strictly conforms to
         * a Firebase Auth UID, rejecting fragile transformed emails or invalid formats.
         * Eliminates email.replace(".", "_") as a document key authority.
         */
        fun isValidFirestoreUserUid(uid: String?): Boolean {
            if (uid.isNullOrBlank()) return false
            if (uid.startsWith("usr_") || uid.startsWith("offline_") || uid.startsWith("goog_") || uid == "guest") return false
            // Derived email strings typically contain '@', '.', or end with domain extensions like '_com', '_org' from email.replace(".", "_")
            if (uid.contains("@") || uid.contains(".")) return false
            if (uid.matches(Regex(".*_[a-zA-Z0-9]+_(com|org|net|edu|gov|io|app|co|uk|de|dev|ai|me|info|biz)$", RegexOption.IGNORE_CASE))) return false // e.g. abc_gmail_com
            return true
        }

        /**
         * Resolves the OAuth 2.0 Web Client ID required by Google Credential Manager (GetGoogleIdOption).
         * Priority order:
         * 1. String resource `default_web_client_id` (auto-generated by com.google.gms.google-services if oauth_client type 3 is present in google-services.json)
         * 2. String resource `google_web_client_id` (explicitly defined in strings.xml)
         */
        fun getWebClientId(context: Context): String? {
            val defaultResId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
            if (defaultResId != 0) {
                val value = context.getString(defaultResId).trim()
                if (value.isNotBlank()) return value
            }
            val explicitResId = context.resources.getIdentifier("google_web_client_id", "string", context.packageName)
            if (explicitResId != 0) {
                val value = context.getString(explicitResId).trim()
                if (value.isNotBlank()) return value
            }
            return null
        }
    }

    val isFirebaseInitialized: Boolean
        get() = try {
            if (FirebaseApp.getApps(context).isEmpty()) {
                FirebaseApp.initializeApp(context)
            }
            FirebaseApp.getApps(context).isNotEmpty()
        } catch (e: Exception) {
            Log.e(TAG, "Error initializing Firebase", e)
            false
        }

    val currentUser: FirebaseUser?
        get() = if (isFirebaseInitialized) {
            try {
                FirebaseAuth.getInstance().currentUser
            } catch (e: Exception) {
                null
            }
        } else null

    /**
     * Sign in with existing Firebase credentials.
     * Firebase UID is the canonical identity authority.
     */
    suspend fun signIn(email: String, password: String): FirebaseSyncResult {
        if (!isFirebaseInitialized) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.OFFLINE_MODE,
                message = "Firebase Auth is unconfigured or offline. Running in local offline mode (no remote Firebase session).",
                uid = null,
                email = email.trim(),
                displayName = email.substringBefore("@").replaceFirstChar { it.uppercase() },
                isEmailVerified = false
            )
        }
        return try {
            val auth = FirebaseAuth.getInstance()
            val result = auth.signInWithEmailAndPassword(email.trim(), password.trim()).await()
            val user = result.user
            val uid = user?.uid
            if (user == null || uid.isNullOrBlank()) {
                throw IllegalStateException("Firebase user or UID is null/blank after signIn.")
            }
            FirebaseSyncResult(
                status = FirebaseSyncStatus.REAL_SUCCESS,
                message = "Signed in as ${user.email ?: email}.",
                uid = uid,
                email = user.email ?: email.trim(),
                displayName = user.displayName ?: email.substringBefore("@").replaceFirstChar { it.uppercase() },
                isEmailVerified = user.isEmailVerified
            )
        } catch (e: Exception) {
            Log.e(TAG, "Firebase signIn failed", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Invalid email or password."
            )
        }
    }

    /**
     * Create new user and send email verification.
     * Firebase UID is generated and returned as the authority.
     */
    suspend fun signUp(email: String, password: String, name: String = ""): FirebaseSyncResult {
        if (!isFirebaseInitialized) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.OFFLINE_MODE,
                message = "Firebase Auth is unconfigured or offline. Created local offline profile (no remote Firebase account created).",
                uid = null,
                email = email.trim(),
                displayName = if (name.isNotBlank()) name else email.substringBefore("@").replaceFirstChar { it.uppercase() },
                isEmailVerified = false
            )
        }
        return try {
            val auth = FirebaseAuth.getInstance()
            val result = auth.createUserWithEmailAndPassword(email.trim(), password.trim()).await()
            val user = result.user
            val uid = user?.uid
            if (user == null || uid.isNullOrBlank()) {
                throw IllegalStateException("Firebase user or UID is null/blank after signUp.")
            }
            if (name.isNotBlank()) {
                try {
                    val profileUpdates = com.google.firebase.auth.UserProfileChangeRequest.Builder()
                        .setDisplayName(name.trim())
                        .build()
                    user.updateProfile(profileUpdates).await()
                } catch (pe: Exception) {
                    Log.w(TAG, "Could not set user displayName", pe)
                }
            }
            var emailSent = false
            try {
                user.sendEmailVerification().await()
                emailSent = true
            } catch (ve: Exception) {
                Log.w(TAG, "Verification email note: ${ve.message}")
            }
            val verificationNote = if (emailSent) " Verification email sent to $email." else ""
            FirebaseSyncResult(
                status = FirebaseSyncStatus.REAL_SUCCESS,
                message = "Account created.$verificationNote Please check your inbox and tap the link to verify.",
                uid = uid,
                email = user.email ?: email.trim(),
                displayName = if (name.isNotBlank()) name else (user.displayName ?: email.substringBefore("@").replaceFirstChar { it.uppercase() }),
                isEmailVerified = false
            )
        } catch (e: Exception) {
            Log.e(TAG, "Firebase signUp failed", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Could not register account."
            )
        }
    }

    /**
     * Official Google Credential Manager Authentication Flow:
     * Google Credential Manager -> Google ID Token -> FirebaseAuth.signInWithCredential() -> FirebaseUser.uid
     *
     * Handles:
     * - User cancellation (GetCredentialCancellationException)
     * - Missing Google credential / account (NoCredentialException)
     * - Invalid credential / ID token parse error (GoogleIdTokenParsingException, FirebaseAuthInvalidCredentialsException)
     * - Firebase authentication failure (FirebaseAuthException)
     * - Network failure (FirebaseNetworkException, IOException)
     */
    suspend fun signInWithGoogle(activityContext: Context): FirebaseSyncResult {
        if (!isFirebaseInitialized) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Firebase Auth is not initialized or offline."
            )
        }

        val webClientId = getWebClientId(activityContext)
        if (webClientId.isNullOrBlank()) {
            val errorMsg = "Google Sign-In configuration missing: OAuth 2.0 Web Client ID ('default_web_client_id') not found. Please enable Google Sign-In in Firebase Console and ensure google-services.json includes oauth_client."
            Log.e(TAG, errorMsg)
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = errorMsg
            )
        }

        return try {
            val credentialManager = CredentialManager.create(activityContext)
            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(webClientId)
                .setAutoSelectEnabled(false)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val response = credentialManager.getCredential(
                context = activityContext,
                request = request
            )

            val credential = response.credential
            if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken
                if (idToken.isBlank()) {
                    return FirebaseSyncResult(
                        status = FirebaseSyncStatus.ERROR,
                        message = "Google Sign-In returned an empty ID token."
                    )
                }
                signInWithGoogleIdToken(idToken)
            } else {
                FirebaseSyncResult(
                    status = FirebaseSyncStatus.ERROR,
                    message = "Unexpected credential type returned from Google Credential Manager: ${credential::class.java.simpleName}"
                )
            }
        } catch (e: GetCredentialCancellationException) {
            Log.d(TAG, "Google Sign-In cancelled by user", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Google Sign-In was cancelled."
            )
        } catch (e: NoCredentialException) {
            Log.e(TAG, "No Google credentials available on device", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "No Google account found on device. Please add a Google account in device settings."
            )
        } catch (e: GoogleIdTokenParsingException) {
            Log.e(TAG, "Failed to parse Google ID token credential", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Invalid Google credential format received."
            )
        } catch (e: GetCredentialException) {
            Log.e(TAG, "Credential Manager failure: ${e.type}", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Google Sign-In failed."
            )
        } catch (e: FirebaseNetworkException) {
            Log.e(TAG, "Network error during Google Sign-In", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Network error during Google Sign-In. Please check your internet connection."
            )
        } catch (e: FirebaseAuthInvalidCredentialsException) {
            Log.e(TAG, "Invalid Firebase credential from Google ID token", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "The Google credential was invalid or expired."
            )
        } catch (e: FirebaseAuthException) {
            Log.e(TAG, "Firebase authentication failure", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Firebase authentication failed."
            )
        } catch (e: java.io.IOException) {
            Log.e(TAG, "IO / Network error during Google authentication", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Network communication failed. Please check your connection."
            )
        } catch (e: Exception) {
            Log.e(TAG, "Unexpected error in signInWithGoogle", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Google Sign-In failed."
            )
        }
    }

    /**
     * Authenticates with Firebase using a verified Google ID token.
     * GoogleAuthProvider.getCredential(idToken, null) -> FirebaseAuth.signInWithCredential() -> currentUser.uid
     */
    suspend fun signInWithGoogleIdToken(idToken: String): FirebaseSyncResult {
        if (!isFirebaseInitialized) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Firebase Auth is not initialized or offline."
            )
        }
        if (idToken.isBlank()) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Google ID token cannot be blank."
            )
        }

        return try {
            val auth = FirebaseAuth.getInstance()
            val credential = GoogleAuthProvider.getCredential(idToken, null)
            val authResult = auth.signInWithCredential(credential).await()
            val currentUser = auth.currentUser
                ?: authResult.user
                ?: throw IllegalStateException("Firebase currentUser is null after successful authentication.")

            val uid = currentUser.uid
            if (uid.isBlank()) {
                throw IllegalStateException("FirebaseAuth currentUser.uid is blank.")
            }

            FirebaseSyncResult(
                status = FirebaseSyncStatus.REAL_SUCCESS,
                message = "Authenticated with Google (${currentUser.email ?: "Account"}).",
                uid = uid,
                email = currentUser.email,
                displayName = currentUser.displayName,
                isEmailVerified = currentUser.isEmailVerified
            )
        } catch (e: FirebaseNetworkException) {
            Log.e(TAG, "Network error during Firebase credential exchange", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Network error during authentication. Please check your internet connection."
            )
        } catch (e: FirebaseAuthInvalidCredentialsException) {
            Log.e(TAG, "Invalid Google credential provided to Firebase", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "The Google authentication token was rejected by Firebase."
            )
        } catch (e: FirebaseAuthException) {
            Log.e(TAG, "FirebaseAuthException during Google sign-in", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Firebase authentication failed."
            )
        } catch (e: java.io.IOException) {
            Log.e(TAG, "IO error during Firebase sign-in", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Network communication failed. Please check your connection."
            )
        } catch (e: Exception) {
            Log.e(TAG, "Firebase signInWithCredential failed", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Google authentication failed."
            )
        }
    }

    /**
     * Refresh user and check email verification status via Firebase reload().
     * NEVER returns true when Firebase is unconfigured or offline.
     */
    suspend fun checkEmailVerification(): Boolean {
        if (!isFirebaseInitialized) return false
        return try {
            val user = FirebaseAuth.getInstance().currentUser ?: return false
            user.reload().await()
            user.isEmailVerified
        } catch (e: Exception) {
            Log.w(TAG, "Could not check email verification", e)
            false
        }
    }

    /**
     * Send password reset link to user's registered email via Firebase.
     * Never falsely reports success when Firebase is not configured.
     */
    suspend fun sendPasswordReset(email: String): FirebaseSyncResult {
        if (!isFirebaseInitialized) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.OFFLINE_MODE,
                message = "Firebase Auth is unconfigured or offline. Cannot send password reset email in offline mode."
            )
        }
        return try {
            FirebaseAuth.getInstance().sendPasswordResetEmail(email.trim()).await()
            FirebaseSyncResult(
                status = FirebaseSyncStatus.REAL_SUCCESS,
                message = "Password reset link sent to $email."
            )
        } catch (e: Exception) {
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Could not send password reset email."
            )
        }
    }

    fun signOut() {
        if (isFirebaseInitialized) {
            try {
                FirebaseAuth.getInstance().signOut()
            } catch (e: Exception) {
                Log.w(TAG, "Sign out error", e)
            }
        }
    }

    /**
     * Optional testing hook to simulate remote Firebase deletion outcomes
     * (e.g. success, requires-recent-login, cloud deletion failure, network error).
     */
    var deleteAccountResolverForTesting: (suspend () -> FirebaseSyncResult)? = null

    /**
     * Requirement 24: Delete user account, Firestore documents, and invoke local cleanup.
     * Guarantees that remote deletion succeeds before triggering local cleanup.
     */
    suspend fun deleteAccount(onLocalCleanup: (suspend () -> Unit)? = null): FirebaseSyncResult {
        deleteAccountResolverForTesting?.let { resolver ->
            val res = resolver.invoke()
            if (res.status == FirebaseSyncStatus.REAL_SUCCESS || res.status == FirebaseSyncStatus.OFFLINE_MODE) {
                onLocalCleanup?.invoke()
            }
            return res
        }

        if (!isFirebaseInitialized) {
            onLocalCleanup?.invoke()
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.OFFLINE_MODE,
                message = "Firebase is unconfigured or offline. Local session data and device storage reset."
            )
        }
        return try {
            val user = FirebaseAuth.getInstance().currentUser
            val uid = user?.uid
            if (uid != null) {
                try {
                    FirebaseFirestore.getInstance().collection("users").document(uid).delete().await()
                } catch (fe: Exception) {
                    Log.w(TAG, "Firestore doc delete error: ${fe.message}")
                }
            }
            if (user != null) {
                user.delete().await()
            }
            onLocalCleanup?.invoke()
            FirebaseSyncResult(
                status = FirebaseSyncStatus.REAL_SUCCESS,
                message = "Firebase account, cloud data, and local storage deleted."
            )
        } catch (e: Exception) {
            Log.e(TAG, "Account deletion failed", e)
            val isReauthNeeded = e is com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException ||
                    (e.message?.contains("recent", ignoreCase = true) == true) ||
                    (e.message?.contains("re-authenticate", ignoreCase = true) == true) ||
                    (e.message?.contains("CREDENTIAL_TOO_OLD", ignoreCase = true) == true) ||
                    (e.message?.contains("requires-recent-login", ignoreCase = true) == true)
            val msg = if (isReauthNeeded) {
                "Re-authentication required. Please sign in again before deleting your account."
            } else {
                e.localizedMessage ?: "Failed to delete remote account."
            }
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = msg
            )
        }
    }

    /**
     * Send email verification link to user's registered email via Firebase Auth.
     * Never falsely reports success when Firebase is not configured.
     */
    suspend fun sendEmailVerification(email: String? = null, password: String? = null): FirebaseSyncResult {
        if (!isFirebaseInitialized) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.OFFLINE_MODE,
                message = "Firebase Auth is unconfigured or offline. Real email verification requires active Firebase."
            )
        }

        return try {
            val auth = FirebaseAuth.getInstance()
            val user = auth.currentUser ?: if (!email.isNullOrBlank() && !password.isNullOrBlank()) {
                auth.signInWithEmailAndPassword(email.trim(), password.trim()).await().user
            } else null

            if (user == null) {
                return FirebaseSyncResult(
                    status = FirebaseSyncStatus.ERROR,
                    message = "No active Firebase user session found to send verification email."
                )
            }

            user.sendEmailVerification().await()
            FirebaseSyncResult(
                status = FirebaseSyncStatus.REAL_SUCCESS,
                message = "Verification email sent to ${user.email}. Tap the link in your email to verify."
            )
        } catch (e: Exception) {
            Log.e(TAG, "Failed to send verification email", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Failed to send email verification."
            )
        }
    }

    /**
     * Requirement 22 & 23: Sync habit completion and profile telemetry to Firestore.
     * Document ID in collection "users" strictly uses Firebase UID:
     * FirebaseAuth.getInstance().currentUser!!.uid
     *
     * Requirement 23: Firestore is strictly habit telemetry and NEVER an entitlement authority.
     * Client-side booleans (e.g. isPro) are NEVER synced as cloud truth.
     * Pro access is determined exclusively by RevenueCat / Google Play Billing receipts.
     */
    suspend fun syncProfileToCloud(
        userId: String? = null,
        wakeTime: String,
        focusGoal: String,
        streakDays: Int,
        completedItems: Set<String>
    ): FirebaseSyncResult {
        if (!isFirebaseInitialized) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.OFFLINE_MODE,
                message = "Firebase is unconfigured or offline. Cloud sync skipped (offline mode)."
            )
        }

        // Canonical identity authority: FirebaseAuth currentUser UID
        val canonicalUid = currentUser?.uid ?: userId

        if (!isValidFirestoreUserUid(canonicalUid)) {
            return FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = "Invalid Firestore document ID. Cloud sync strictly requires an authenticated Firebase UID, never a transformed email."
            )
        }

        val nonNullUid = canonicalUid!!

        return try {
            val db = FirebaseFirestore.getInstance()
            val userDoc = mapOf(
                "uid" to nonNullUid,
                "wakeTime" to wakeTime,
                "focusGoal" to focusGoal,
                "streakDays" to streakDays,
                "lastSyncTimestamp" to System.currentTimeMillis(),
                "completedToday" to completedItems.toList()
            )
            db.collection("users").document(nonNullUid)
                .set(userDoc, SetOptions.merge())
                .await()

            FirebaseSyncResult(
                status = FirebaseSyncStatus.REAL_SUCCESS,
                message = "Cloud sync complete (Cloud Firestore document: /users/$nonNullUid)."
            )
        } catch (e: Exception) {
            Log.e(TAG, "Firestore sync error", e)
            FirebaseSyncResult(
                status = FirebaseSyncStatus.ERROR,
                message = e.localizedMessage ?: "Firestore sync error."
            )
        }
    }
}
